### ISSUE TITLE
您好，请教一下几个问题

### ISSUE THREAD

**Issue by Past-GuoWang** [aixed/WeChat-Hook#96]
最新版的dll 测试json的接口可以正常使用 文档内的接口大部分不能使用

**Comment by aixed** [comment]
文档里面的那个是付费版的接口

**Comment by qwerty6688** [comment]
兄弟小心。这个是骗子，已经好多人上当了！
https://github.com/Fate0x01/aixed-WeChat-Hook

**Comment by qwerty6688** [comment]
这是骗子！！！小心上当：
骗子信息曝光网址：https://bbs.125.la/thread-14755083-1-1.html

内容摘要：
曝光骗子最新QQ。Apricity(850040076);骗子账号真多，都是为了骗钱才准备的吧。老骗子了。这骗子这辈子的都吃不上四个菜。   河南省商丘市  发表于 2022-12-7 16:03
 一杯凉酒
我认同一部分人的看法，那些说贪便宜的不敢恭维， 购买之前也都并却说明了   云南省昆明市  发表于 2022-11-29 17:48
 陽陽陽
有人看没看到买断？你管他贪不贪 赚不赚 干什么。   美国  发表于 2022-11-29 00:06
 刘一缘
骗子最新的主页：https://github.com/aixed   广东省揭阳市  发表于 2022-11-28 17:04
 木小果
自己说买断制还限制人家怎样使用？懂不懂什么叫买断制，还能有人在这洗啊，九年义务教育上完了吗看不懂汉字？你管人家有没有赚回来   湖南省株洲市  发表于 2022-11-27 11:57
 刘一缘
专门为这个骗子建的仓库 https://github.com/Fate0x01/aixed-WeChat-Hook   广东省揭阳市  发表于 2022-11-26 02:23
 刘一缘
骗子其他QQ ： 850040076   广东省揭阳市  发表于 2022-11-25 15:09
 刘一缘
@huxian 我只能说，我千有错万有错，就是信错人。其他我一点错都没有，也甭管赚没赚回来，说出去的话没做到位，这是这位跑路的作者人品不行。   广东省揭阳市  发表于 2022-11-24 23:53
 huxian
实话实说，楼主的理由可圈可点站的住脚，但是道理千千万万都逃避不了人性的贪婪。   广东省肇庆市  发表于 2022-11-24 23:25
 huxian
我想说用了3个月了也不亏，应该你也赚回来了，只是VX更新频繁，500想永久持续使用，应该不太可能，作者应该不耍。   广东省肇庆市  发表于 2022-11-24 23:14
 陈宁
自己说买断制还限制人家怎样使用？懂不懂什么叫买断制，还能有人在这洗啊，九年义务教育上完了吗看不懂汉字   广西壮族自治区南宁市  发表于 2022-11-24 21:11
 人间疾苦
答应的买断 就是买断 现在出尔反尔就是人品问题   四川省成都市  发表于 2022-11-24 20:29
 

最新QQ:Apricity(850040076);认清骗子嘴脸，不要在被骗。

骗子最新qq:850040076，骗子所在QQ群：927825838。
这种骗子就应该天打雷轰。我也被骗了。还好我交易走的平台，申请退款了。
兄弟，你消消气，这些钱就当是给他亲人的烧*钱。

跑路狗最新资料：
姓名：黄威
手机号：15089062194
就职于西藏那曲镇新电视台，政府职员

已经掌握骗子最新QQ证据，并已提交公安系统。等待骗子被抓。坐等后续更新，拭目以待。

到现在骗子的师父还在拼命的给骗子洗地。还有骗子的走狗一直在帮骗子洗地。大家都看清楚这些人的嘴脸。千万不要上当受骗。


骗子已经换了QQ，不过还是被拔出来了，骗子最新QQ 850040076，骗子所在QQ群927825838
[img]https://pic.imgdb.cn/item/638f1387b1fccdcd36549412.png
